### ISSUE TITLE
无法初始化该PhoneNumberLookUp，抛出异常

### ISSUE THREAD

**Issue by wutongshu-master** [EeeMt/phone-number-geo#3]
[ERROR threadPoolTaskScheduler-33 2020-08-27 11:35:30,232 --146919999(ms)]
[me.ihxq.projects.pna.PhoneNumberLookup.init(PhoneNumberLookup.java:47)]
 failed to init PhoneNumberLookUp
java.io.IOException: Stale file handle
        at java.io.RandomAccessFile.readBytes(Native Method)
        at java.io.RandomAccessFile.read(RandomAccessFile.java:377)
        at org.springframework.boot.loader.data.RandomAccessDataFile$DataInputStream.doRead(RandomAccessDataFile.java:184)
        at org.springframework.boot.loader.data.RandomAccessDataFile$DataInputStream.read(RandomAccessDataFile.java:152)
        at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:238)
        at org.springframework.boot.loader.jar.ZipInflaterInputStream.fill(ZipInflaterInputStream.java:62)
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
        at org.springframework.boot.loader.jar.ZipInflaterInputStream.read(ZipInflaterInputStream.java:52)
        at java.io.FilterInputStream.read(FilterInputStream.java:107)
        at me.ihxq.projects.pna.PhoneNumberLookup.init(PhoneNumberLookup.java:35)
        at me.ihxq.projects.pna.PhoneNumberLookup.<init>(PhoneNumberLookup.java:64)
        at me.ihxq.projects.pna.PhoneNumberLookup.<init>(PhoneNumberLookup.java:56)

**Comment by EeeMt** [comment]
什么环境下出现的呢? ide, jar包(java -jar)还是什么?

**Comment by wutongshu-master** [comment]
linux环境下，重新发布下就OK了，但是现在又出现这种情况

**Comment by wutongshu-master** [comment]
请问有解决办法吗，今天又出现了

**Comment by EeeMt** [comment]
我google了一下报错信息, 对于`Stale file handle`的解释可以参考如下解释:
> When the directory is deleted, the inode for that directory (and the inodes for its contents) are recycled. The pointer your shell has to that directory's inode (and its contents's inodes) are now no longer valid. When the directory is restored from backup, the old inodes are not (necessarily) reused; the directory and its contents are stored on random inodes. The only thing that stays the same is that the parent directory reuses the same name for the restored directory (because you told it to).
> 
> Now if you attempt to access the contents of the directory that your original shell is still pointing to, it communicates that request to the file system as a request for the original inode, which has since been recycled (and may even be in use for something entirely different now). So you get a stale file handle message because you asked for some nonexistent data.
> 
> When you perform a cd operation, the shell reevaluates the inode location of whatever destination you give it. Now that your shell knows the new inode for the directory (and the new inodes for its contents), future requests for its contents will be valid.
> 出处:  [What does 'stale file handle' in Linux mean?](https://stackoverflow.com/questions/20105260/what-does-stale-file-handle-in-linux-mean)

猜测可能的原因: jar包(或者其父目录)被删除, 或者删除了又恢复了(inode已改变, 参考上文引用); 或者重新发版的过程是先覆盖jar包再重启服务;
另外很多帖子提到了nfs, 不知道你是不是把jar放在nfs上的, 如果是的话, 可以尝试更改存储位置.

**Comment by wutongshu-master** [comment]
谢谢回复，因为jar包里存在log日志文件，建议剔除噢

**Comment by EeeMt** [comment]
是说我传到maven仓库的jar包里有日志文件吗, 没有啊
